spring.application.name=sb-ecom

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

project.image = images/


spring.app.jwtSecret=mySecretKey123912738dnbsabjkfhjdkahajkbxasddccnbdnmshadgbnxzcvcnsxmsasx
spring.app.jwtExpirationMs=3000000

spring.ecom.app.jwtCookieName=springBootEcom

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.eccomerce.project=DEBUG


















#Dependencies in the project in order
# 1. spring web
# 2. data jpa
# 3. h2-database
# 4. Lombok
# 5. Validation (hibernate Validator)
# 6. Model Mapper (from its official website)
# 7. spring security
# 8. Jwt (from GitHub)






